version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=123456
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fastapi
    # For presisting data in database
    volumes:
      - postres-db=/var/lib/postgresql/data
# Anytime you create volume you need another volume section globely

volumes:
  postgres-db:
