"""add phone number to user

Revision ID: d371b07d4d13
Revises: 8705b0415313
Create Date: 2023-03-30 16:39:14.936324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd371b07d4d13'
down_revision = '8705b0415313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_numer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_numer')
    # ### end Alembic commands ###
